# Generated by Django 2.1.1 on 2018-10-29 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_useraddcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='consume_total',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.CourseLevel'),
        ),
        migrations.AlterField(
            model_name='course',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Machine'),
        ),
        migrations.AlterField(
            model_name='course',
            name='minute_avg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.CoursePicture'),
        ),
        migrations.AlterField(
            model_name='course',
            name='recipes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipesPlan'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.CourseType'),
        ),
    ]
