# Generated by Django 2.1.1 on 2018-10-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_goodpicture_size'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='goods',
        #     old_name='note1',
        #     new_name='kucun',
        # ),
        # migrations.RemoveField(
        #     model_name='goods',
        #     name='note2',
        # ),
        migrations.AddField(
            model_name='goods',
            name='gooddesc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='goodpicture',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
