# Generated by Django 2.1.1 on 2018-10-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181028_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcommentreply',
            name='checked',
        ),
    ]
