# Generated by Django 2.1.1 on 2018-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_shopcommentlike_shopcommentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goodcounts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
