# Generated by Django 2.1.1 on 2018-10-17 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('info', models.CharField(max_length=1000)),
                ('times', models.CharField(max_length=50)),
                ('note1', models.CharField(max_length=50, null=True)),
                ('note2', models.CharField(max_length=50, null=True)),
                ('note3', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionMusclePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('note1', models.CharField(max_length=50, null=True)),
                ('note2', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionYaolingtu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('note1', models.CharField(max_length=50, null=True)),
                ('note2', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.CharField(max_length=50, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.ActionLibrary')),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
