# Generated by Django 2.1.1 on 2018-10-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20181017_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
