# Generated by Django 2.1.1 on 2018-10-19 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_actionpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlibrary',
            name='picture',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='action.ActionPicture'),
        ),
    ]
