# Generated by Django 2.1.1 on 2018-10-17 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecipesFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Food')),
            ],
        ),
        migrations.CreateModel(
            name='RecipesPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calorie', models.CharField(max_length=50)),
                ('breakfast', models.CharField(max_length=50, null=True)),
                ('lunch', models.CharField(max_length=50, null=True)),
                ('dinner', models.CharField(max_length=50, null=True)),
                ('info', models.CharField(max_length=255)),
                ('note1', models.CharField(max_length=50, null=True)),
                ('note2', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipesfood',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipesPlan'),
        ),
        migrations.AddField(
            model_name='recipesfood',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.FoodType'),
        ),
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.FoodType'),
        ),
    ]
