# Generated by Django 2.1.1 on 2018-10-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sex',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
