# Generated by Django 2.1.1 on 2018-10-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_sex_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='recievename',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='telephone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='youbian',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
