# Generated by Django 2.1.1 on 2018-10-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_addgood_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='addgood',
            name='checked',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
